### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Viresh-R** [kachiO/class-agnostic-counting-pytorch#1]
Hey,
any chance you could share your pre-trained imagenet vid model ? I need to apply it to a different task, and would be great to get the pretrained model.

Thanks,
Viresh

**Comment by kachiO** [comment]
Hey Viresh,

I forgot to save the weights to my local machine and the repo. I no longer
have access to machine on which I used to train. A possible workaround to
not training the model yourself is to load the pretrained weights from the
original author’s keras model. There are a few examples online on how to do
this, one that comes to mind is from [HuggingFace](
https://medium.com/huggingface/from-tensorflow-to-pytorch-265f40ef2a28).
Good luck,

Kachi

**Comment by Viresh-R** [comment]
Hi Kachi,
Thanks for the suggestion ! I ended up using the original Keras training code from authors. Anyways, issue resolved 👍

Viresh
