### ISSUE TITLE
pretraining total time

### ISSUE THREAD

**Issue by weicheng113** [kachiO/class-agnostic-counting-pytorch#3]
Thanks for porting to pytorch. 

I wonder if you remember roughly how long it took you to pretrain the network with ImageNet VID dataset(also with what kinds of machine configuration). I went through the issue list. I knew that you forgot to have pretrained weight uploaded. There are two options for me. One is to pretrain it and another is to somehow load the weight from the original keras version. I would like to get rough idea for the first option. If it is not too much, I may take the first option(also take the opportunity to get similar with pretrain part, which I may need for my own domain). 

Thanks,
Cheng

**Comment by kachiO** [comment]
I don't remember exactly. It might've been under two days.

**Comment by weicheng113** [comment]
Thanks @kachiO . That sounds good. Two days' training time is affordable.
